---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "test/kitchen/data_bags"

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[spring-petclinic-app-deploy::default]
    attributes:
